import { assertEquals } from "jsr:@std/assert@1";
import { KvExplorer } from "../lib/KvExplorer.ts";

Deno.test("KvExplorer - BigInt Cursor Bug", async () => {
  const db = await Deno.openKv(":memory:");
  const explorer = new KvExplorer(db);

  // Setup: 2 records with bigint keys
  await db.set(["big", 1n], "val1");
  await db.set(["big", 2n], "val2");

  // This should NOT throw, but it likely will because of JSON.stringify(bigint)
  const result = await explorer.getRecords(["big"], { limit: 1 });
  assertEquals(result.records.length, 1);

  // result.cursor is generated by JSON.stringify(next.key)
  // If it contains a bigint, it will throw during stringify.

  db.close();
});

Deno.test("KvExplorer - Uint8Array Cursor Bug", async () => {
  const db = await Deno.openKv(":memory:");
  const explorer = new KvExplorer(db);

  // Setup: 2 records with Uint8Array keys
  const u8_1 = new Uint8Array([1]);
  const u8_2 = new Uint8Array([2]);
  await db.set(["u8", u8_1], "val1");
  await db.set(["u8", u8_2], "val2");

  const result = await explorer.getRecords(["u8"], { limit: 1 });
  assertEquals(result.records.length, 1);

  // result.cursor is JSON.stringify([ "u8", { "0": 2 } ]) or similar
  // When used in next call, it will be JSON.parsed to [ "u8", { "0": 2 } ]
  // which is NOT a Uint8Array.

  const result2 = await explorer.getRecords(["u8"], {
    limit: 1,
    cursor: result.cursor,
  });

  // If the bug exists, result2 might be empty or throw because the cursor is invalid
  assertEquals(result2.records.length, 1);
  assertEquals(result2.records[0].value.value, "val2");

  db.close();
});
